/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.5
 * Generated at: 2025-05-08 10:28:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Menu;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.example.menu.foodapp.FoodItem;
import com.example.menu.foodapp.FoodItemFileUtil;
import java.util.List;
import java.util.ArrayList;

public final class MenuPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.example.menu.foodapp.FoodItem");
    _jspx_imports_classes.add("com.example.menu.foodapp.FoodItemFileUtil");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Food Menu</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/Menu/styles.css\">\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("    .store-tag {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      background-color: #f0f0f0;\r\n");
      out.write("      color: #555;\r\n");
      out.write("      padding: 4px 10px;\r\n");
      out.write("      border-radius: 15px;\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      margin: 5px 0;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      border: 1px solid #ddd;\r\n");
      out.write("    }\r\n");
      out.write("    .food-card {\r\n");
      out.write("      position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    .cart-notification {\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      bottom: 20px;\r\n");
      out.write("      right: 20px;\r\n");
      out.write("      background-color: #28a745;\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 15px 25px;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      box-shadow: 0 3px 10px rgba(0,0,0,0.2);\r\n");
      out.write("      z-index: 1000;\r\n");
      out.write("      transition: opacity 0.5s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .fade-out {\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/Header/HeaderBar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div class=\"header2\">\r\n");
      out.write("    <h1>Our Delicious Menu</h1>\r\n");
      out.write("    <div class=\"cart-summary\">\r\n");
      out.write("      <a href=\"CartPage.jsp\" id=\"cartLink\">Cart (<span id=\"cartCount\">0</span>)</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <form method=\"get\" action=\"MenuPage.jsp\" class=\"search-sort-container\">\r\n");
      out.write("    <input type=\"text\" id=\"search\" name=\"search\" placeholder=\"Search for food items...\"\r\n");
      out.write("           value=\"");
      out.print( request.getParameter("search") != null ? request.getParameter("search") : "" );
      out.write("\" />\r\n");
      out.write("    <button type=\"submit\" name=\"sort\" value=\"price\" class=\"sort-btn\">Sort by Price</button>\r\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"menu-grid\" id=\"menuGrid\">\r\n");
      out.write("    ");

      ServletContext applicationContext = request.getServletContext();
      List<FoodItem> foodItems = FoodItemFileUtil.loadFoodItems(applicationContext);

      // Apply sorting if requested
      if ("price".equals(request.getParameter("sort"))) {
        foodItems.sort((a, b) -> Double.compare(a.getPrice(), b.getPrice()));
      }

      // Apply search filter if provided
      String searchTerm = request.getParameter("search");
      if (searchTerm != null && !searchTerm.isEmpty()) {
        List<FoodItem> filteredItems = new ArrayList<>();
        for (FoodItem item : foodItems) {
          if (item.getName().toLowerCase().contains(searchTerm.toLowerCase()) ||
                  item.getStoreName().toLowerCase().contains(searchTerm.toLowerCase())) {
            filteredItems.add(item);
          }
        }
        foodItems = filteredItems;
      }

      if (foodItems.isEmpty()) {
    
      out.write("\r\n");
      out.write("    <div class=\"no-results\">No food items found matching your search.</div>\r\n");
      out.write("    ");

    } else {
      for (FoodItem item : foodItems) {
    
      out.write("\r\n");
      out.write("    <div class=\"food-card\" data-id=\"");
      out.print( item.getName().hashCode() );
      out.write("\">\r\n");
      out.write("      <img src=\"");
      out.print( item.getImagePath() );
      out.write("\" alt=\"");
      out.print( item.getName() );
      out.write("\" class=\"food-image\">\r\n");
      out.write("      <div class=\"food-info\">\r\n");
      out.write("        <h3 class=\"food-name\">");
      out.print( item.getName() );
      out.write("</h3>\r\n");
      out.write("        <span class=\"store-tag\">");
      out.print( item.getStoreName() );
      out.write("</span>\r\n");
      out.write("        <p class=\"food-price\">LKR ");
      out.print( String.format("%.2f", item.getPrice()) );
      out.write("</p>\r\n");
      out.write("        <button class=\"add-to-cart\"\r\n");
      out.write("                data-name=\"");
      out.print( item.getName() );
      out.write("\"\r\n");
      out.write("                data-price=\"");
      out.print( item.getPrice() );
      out.write("\"\r\n");
      out.write("                data-image=\"");
      out.print( item.getImagePath() );
      out.write("\"\r\n");
      out.write("                data-store=\"");
      out.print( item.getStoreName() );
      out.write("\">\r\n");
      out.write("          Add to Cart\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

        }
      }
    
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  // Initialize cart from sessionStorage\r\n");
      out.write("  let cart = JSON.parse(sessionStorage.getItem('cart')) || [];\r\n");
      out.write("  updateCartCount();\r\n");
      out.write("\r\n");
      out.write("  // Client-side search\r\n");
      out.write("  document.getElementById('search').addEventListener('input', function(e) {\r\n");
      out.write("    const searchTerm = e.target.value.toLowerCase();\r\n");
      out.write("    const foodCards = document.querySelectorAll('.food-card');\r\n");
      out.write("    let hasVisibleItems = false;\r\n");
      out.write("\r\n");
      out.write("    foodCards.forEach(card => {\r\n");
      out.write("      const foodName = card.querySelector('.food-name').textContent.toLowerCase();\r\n");
      out.write("      const storeName = card.querySelector('.store-tag').textContent.toLowerCase();\r\n");
      out.write("      if (foodName.includes(searchTerm) || storeName.includes(searchTerm)) {\r\n");
      out.write("        card.style.display = 'block';\r\n");
      out.write("        hasVisibleItems = true;\r\n");
      out.write("      } else {\r\n");
      out.write("        card.style.display = 'none';\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    const noResults = document.querySelector('.no-results');\r\n");
      out.write("    if (!hasVisibleItems) {\r\n");
      out.write("      if (!noResults) {\r\n");
      out.write("        const menuGrid = document.getElementById('menuGrid');\r\n");
      out.write("        const noResultsDiv = document.createElement('div');\r\n");
      out.write("        noResultsDiv.className = 'no-results';\r\n");
      out.write("        noResultsDiv.textContent = 'No food items found matching your search.';\r\n");
      out.write("        menuGrid.appendChild(noResultsDiv);\r\n");
      out.write("      }\r\n");
      out.write("    } else if (noResults) {\r\n");
      out.write("      noResults.remove();\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  // Add to cart functionality\r\n");
      out.write("  document.querySelectorAll('.add-to-cart').forEach(button => {\r\n");
      out.write("    button.addEventListener('click', function() {\r\n");
      out.write("      const item = {\r\n");
      out.write("        id: this.parentElement.parentElement.getAttribute('data-id'),\r\n");
      out.write("        name: this.getAttribute('data-name'),\r\n");
      out.write("        price: parseFloat(this.getAttribute('data-price')),\r\n");
      out.write("        image: this.getAttribute('data-image'),\r\n");
      out.write("        store: this.getAttribute('data-store'),\r\n");
      out.write("        quantity: 1\r\n");
      out.write("      };\r\n");
      out.write("\r\n");
      out.write("      // Check if item already in cart\r\n");
      out.write("      const existingItem = cart.find(cartItem => cartItem.id === item.id);\r\n");
      out.write("      if (existingItem) {\r\n");
      out.write("        existingItem.quantity += 1;\r\n");
      out.write("      } else {\r\n");
      out.write("        cart.push(item);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // Update session storage\r\n");
      out.write("      sessionStorage.setItem('cart', JSON.stringify(cart));\r\n");
      out.write("      updateCartCount();\r\n");
      out.write("\r\n");
      out.write("      // Show confirmation\r\n");
      out.write("      showAddedToCart(item.name);\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  function updateCartCount() {\r\n");
      out.write("    const count = cart.reduce((total, item) => total + item.quantity, 0);\r\n");
      out.write("    document.getElementById('cartCount').textContent = count;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function showAddedToCart(itemName) {\r\n");
      out.write("    const notification = document.createElement('div');\r\n");
      out.write("    notification.className = 'cart-notification';\r\n");
      out.write("    notification.textContent = `${itemName} added to cart!`;\r\n");
      out.write("    document.body.appendChild(notification);\r\n");
      out.write("\r\n");
      out.write("    setTimeout(() => {\r\n");
      out.write("      notification.classList.add('fade-out');\r\n");
      out.write("      setTimeout(() => notification.remove(), 500);\r\n");
      out.write("    }, 2000);\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
