/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.5
 * Generated at: 2025-05-08 10:28:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Header;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class HeaderBar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<header class=\"header\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/Header/HeaderBar.css\">\r\n");
      out.write("  <div class=\"logo\">\r\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/HomePage/\">\r\n");
      out.write("      <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/Eatzz.png\" alt=\"Eatzz Logo\">\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <nav>\r\n");
      out.write("    <ul class=\"nav-links\">\r\n");
      out.write("      <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/HomePage/\">Home</a></li>\r\n");
      out.write("      <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/Menu/MenuPage.jsp\">Menu</a></li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/cart.jsp\" class=\"cart-link\">\r\n");
      out.write("          Cart <span id=\"headerCartCount\" class=\"cart-count\">0</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- Profile Menu with Dropdown -->\r\n");
      out.write("      <li class=\"profile-menu\">\r\n");
      out.write("        <a href=\"javascript:void(0)\">Profile</a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("          <!-- Smaller View Profile Button -->\r\n");
      out.write("          <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/UserProfile/profile.jsp\">View Profile</a></li>\r\n");
      out.write("          <!-- Improved Logout Button -->\r\n");
      out.write("          <li>\r\n");
      out.write("            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/signout\" method=\"post\" style=\"margin: 0;\">\r\n");
      out.write("              <button type=\"submit\" class=\"logout-button\">Logout</button>\r\n");
      out.write("            </form>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <script>\r\n");
      out.write("    // Function to update cart count in header\r\n");
      out.write("    function updateHeaderCartCount() {\r\n");
      out.write("      const cart = JSON.parse(sessionStorage.getItem('cart')) || [];\r\n");
      out.write("      const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);\r\n");
      out.write("      document.getElementById('headerCartCount').textContent = totalItems;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Update cart count when page loads\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', updateHeaderCartCount);\r\n");
      out.write("\r\n");
      out.write("    // Listen for cart updates from other pages\r\n");
      out.write("    window.addEventListener('storage', function(event) {\r\n");
      out.write("      if (event.key === 'cartUpdated') {\r\n");
      out.write("        updateHeaderCartCount();\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
