/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.5
 * Generated at: 2025-05-05 21:32:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AdminPage;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;

public final class AddUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Add User</title>\r\n");
      out.write("    <!-- Link to Add User CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/AdminPage/AddUser.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Montserrat', sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            background: url('");
      out.print( request.getContextPath() );
      out.write("/images/AdminBg.jpg') no-repeat center center fixed;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    /* Popup container styling */\r\n");
      out.write("        .popup-container {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 20px;\r\n");
      out.write("            right: 20px;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            border-left: 6px solid;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 15px 20px;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("            display: none; /* Hidden by default */\r\n");
      out.write("            font-family: 'Inter', sans-serif;\r\n");
      out.write("            animation: fadeIn 0.5s ease; /* Fade-in animation */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup-container.success {\r\n");
      out.write("            border-color: #4CAF50; /* Green for success */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup-container.error {\r\n");
      out.write("            border-color: #F44336; /* Red for error */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup-container h4 {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup-container p {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin: 5px 0 0 0;\r\n");
      out.write("            color: #555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup-container .close-btn {\r\n");
      out.write("            background: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            color: #999;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 10px;\r\n");
      out.write("            right: 10px;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup-container .close-btn:hover {\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(-15px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"dashboard\">\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <aside class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-logo\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/AdminPage/Eatzz.png\" alt=\"Eatzz Logo\" class=\"logo-image\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"/AdminPage/AdminDashboard.jsp\">🏠 Home</a></li>\r\n");
      out.write("                <li><a href=\"/AdminPage/AddUser.jsp\" class=\"active\">👥 Users</a></li>\r\n");
      out.write("                <li><a href=\"#\">📊 Charts</a></li>\r\n");
      out.write("                <li><a href=\"#\">⚙️ Settings</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <main class=\"main-content\">\r\n");
      out.write("        <section class=\"main-section\">\r\n");
      out.write("            <!-- Add User Header -->\r\n");
      out.write("            <div class=\"section-header\">\r\n");
      out.write("                <h1>Add New User</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Add User Form -->\r\n");
      out.write("            <div class=\"form-container\">\r\n");
      out.write("                <h2>Fill User Details</h2>\r\n");
      out.write("\r\n");
      out.write("                <form method=\"POST\" action=\"");
      out.print( request.getContextPath() );
      out.write("/CreateUserServlet\">\r\n");
      out.write("                    <label for=\"username\">Username:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"username\" name=\"username\" placeholder=\"Enter username\" required>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"password\">Password:</label>\r\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter password\" required>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"email\">Email:</label>\r\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Enter a valid email address\" required>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"phone\">Phone Number:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"phone\" name=\"phone\" placeholder=\"Enter a 10-digit phone number\" required>\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"address\">Address :</label>\r\n");
      out.write("                    <input type=\"text\" id=\"address\" name=\"address\" placeholder=\"Enter Address\" required>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\">Add User</button>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                <!-- Back to Admin Dashboard -->\r\n");
      out.write("                <a href=\"/AdminPage/AdminDashboard.jsp\">🔙 Back to Dashboard</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Popup Element -->\r\n");
      out.write("<div id=\"popupMessage\" class=\"popup-container\">\r\n");
      out.write("    <button class=\"close-btn\" onclick=\"closePopup()\">×</button>\r\n");
      out.write("    <h4 id=\"popupTitle\"></h4>\r\n");
      out.write("    <p id=\"popupBody\"></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Trigger popups for success or error messages from URL parameters\r\n");
      out.write("    window.addEventListener('load', function() {\r\n");
      out.write("        const urlParams = new URLSearchParams(window.location.search);\r\n");
      out.write("        const successMessage = urlParams.get('success');\r\n");
      out.write("        const errorMessage = urlParams.get('error');\r\n");
      out.write("\r\n");
      out.write("        const popup = document.getElementById('popupMessage');\r\n");
      out.write("        const title = document.getElementById('popupTitle');\r\n");
      out.write("        const body = document.getElementById('popupBody');\r\n");
      out.write("\r\n");
      out.write("        if (successMessage) {\r\n");
      out.write("            title.innerText = 'Success';\r\n");
      out.write("            body.innerText = decodeURIComponent(successMessage); // Decode URL-encoded message\r\n");
      out.write("            popup.classList.add('success');\r\n");
      out.write("            popup.style.display = 'block';\r\n");
      out.write("        } else if (errorMessage) {\r\n");
      out.write("            title.innerText = 'Error';\r\n");
      out.write("            body.innerText = decodeURIComponent(errorMessage); // Decode URL-encoded message\r\n");
      out.write("            popup.classList.add('error');\r\n");
      out.write("            popup.style.display = 'block';\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Function to close the popup\r\n");
      out.write("    function closePopup() {\r\n");
      out.write("        const popup = document.getElementById('popupMessage');\r\n");
      out.write("        popup.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
