/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.5
 * Generated at: 2025-05-05 21:32:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AdminPage;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.io.*;

public final class AdminDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // Check if "adminUser" attribute exists in the session; if not, redirect to the login page
    if (session.getAttribute("adminUser") == null) {
        response.sendRedirect(request.getContextPath() + "/AdminPage/admin_login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Admin Dashboard</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/AdminPage/StyleDashboard.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Popup container styling (preserved) */\r\n");
      out.write("        .popup-container {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 20px;\r\n");
      out.write("            right: 20px;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 15px 20px;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("            display: none; /* Hidden by default */\r\n");
      out.write("            font-family: 'Montserrat Medium', sans-serif;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            animation: fadeIn 0.5s ease; /* Smooth fade-in animation */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup-container.success {\r\n");
      out.write("            border-left: 6px solid #4CAF50; /* Green success indicator */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup-container.error {\r\n");
      out.write("            border-left: 6px solid #F44336; /* Red error indicator */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup-container h4 {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            margin: 0 0 5px 0;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup-container p {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            color: #555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup-container .close-btn {\r\n");
      out.write("            background: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            color: #999;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 10px;\r\n");
      out.write("            right: 10px;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup-container .close-btn:hover {\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(-15px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Enhanced user table styles */\r\n");
      out.write("        .user-table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            font-family: 'Montserrat', sans-serif;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-table th,\r\n");
      out.write("        .user-table td {\r\n");
      out.write("            padding: 15px 20px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-table th {\r\n");
      out.write("            background-color: #f4f4f9;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            border-bottom: 2px solid #ddd;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-table tbody tr {\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-table tbody tr:nth-child(even) {\r\n");
      out.write("            background-color: #f9f9f9; /* Striped effect */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-table tbody tr:hover {\r\n");
      out.write("            background-color: #e8f0ff;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Action buttons inside the table */\r\n");
      out.write("        .action-form button {\r\n");
      out.write("            padding: 8px 12px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-family: 'Montserrat Medium', sans-serif;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            box-shadow: 0 3px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            gap: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .action-form button.edit-btn {\r\n");
      out.write("            background-color: #4caf50;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .action-form button.edit-btn:hover {\r\n");
      out.write("            background-color: #43a047;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .action-form button.delete-btn {\r\n");
      out.write("            background-color: #e53935; /* Red */\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .action-form button.delete-btn:hover {\r\n");
      out.write("            background-color: #d32f2f; /* Darker red */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive adjustments for smaller screens */\r\n");
      out.write("        @media only screen and (max-width: 768px) {\r\n");
      out.write("            .user-table {\r\n");
      out.write("                display: block;\r\n");
      out.write("                overflow-x: auto;\r\n");
      out.write("                white-space: nowrap;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .user-table th,\r\n");
      out.write("            .user-table td {\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .action-form button {\r\n");
      out.write("                font-size: 12px;\r\n");
      out.write("                padding: 6px 10px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"dashboard\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <aside class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-logo\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/AdminPage/Eatzz.png\" alt=\"Eatzz Logo\" class=\"logo-image\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"/AdminPage/AdminDashboard.jsp\" class=\"active\">🏠 Home</a></li>\r\n");
      out.write("                <li><a href=\"/AdminPage/AddUser.jsp\">👤 Add User</a></li>\r\n");
      out.write("                <li><a href=\"#\">📊 Charts</a></li>\r\n");
      out.write("                <li><a href=\"#\">⚙️ Settings</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <main class=\"main-content\">\r\n");
      out.write("        <header class=\"top-bar\">\r\n");
      out.write("            <h1>Welcome, Admin!</h1>\r\n");
      out.write("\r\n");
      out.write("            <!-- Search Bar -->\r\n");
      out.write("            <div class=\"search-bar\">\r\n");
      out.write("                <input type=\"text\" id=\"searchInput\" placeholder=\"Search for users...\" onkeyup=\"filterTable()\" />\r\n");
      out.write("                <button type=\"button\">🔍</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"profile-dropdown\">\r\n");
      out.write("                <span><b>");
      out.print( session.getAttribute("adminUser") != null ? session.getAttribute("adminUser") : "Admin" );
      out.write("</b></span>\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/LogoutServlet\">(Logout)</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"main-section\">\r\n");
      out.write("            <!-- Dynamic Popups -->\r\n");
      out.write("            <div id=\"popupMessage\" class=\"popup-container\">\r\n");
      out.write("                <button class=\"close-btn\" onclick=\"closePopup()\">×</button>\r\n");
      out.write("                <h4 id=\"popupTitle\"></h4>\r\n");
      out.write("                <p id=\"popupBody\"></p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h2>User Management</h2>\r\n");
      out.write("\r\n");
      out.write("            <!-- Enhanced User Table -->\r\n");
      out.write("            <table id=\"userTable\" class=\"user-table\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>Username</th>\r\n");
      out.write("                    <th>Email</th>\r\n");
      out.write("                    <th>Phone</th>\r\n");
      out.write("                    <th>Address</th>\r\n");
      out.write("                    <th>Actions</th>\r\n");
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                ");

                    // Code to fetch user data from users.txt
                    String filePath = application.getRealPath("WEB-INF/users.txt");
                    File usersFile = new File(filePath);
                    if (usersFile.exists() && usersFile.canRead()) {
                        try (BufferedReader br = new BufferedReader(new FileReader(usersFile))) {
                            String line;
                            while ((line = br.readLine()) != null) {
                                String[] userDetails = line.split(",");
                                String username = userDetails.length > 0 ? userDetails[0] : "N/A";
                                String email = userDetails.length > 2 ? userDetails[2] : "N/A";
                                String phone = userDetails.length > 3 ? userDetails[3] : "N/A";
                                String address = userDetails.length > 4 ? userDetails[4] : "N/A";
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.print( username );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( email );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( phone );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( address );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <div class=\"action-form\">\r\n");
      out.write("                            <form method=\"GET\" action=\"");
      out.print( request.getContextPath() );
      out.write("/EditUserServlet\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"username\" value=\"");
      out.print( username );
      out.write("\">\r\n");
      out.write("                                <button type=\"submit\" class=\"edit-btn\">Edit</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                            <form method=\"POST\" action=\"");
      out.print( request.getContextPath() );
      out.write("/DeleteUserServlet\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"username\" value=\"");
      out.print( username );
      out.write("\">\r\n");
      out.write("                                <button type=\"submit\" class=\"delete-btn\">Delete</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");
      }
                } catch (IOException e) {
                    out.println("<tr><td colspan='4'>Error reading users file.</td></tr>");
                }
                } else {
                    out.println("<tr><td colspan='4'>No user data available.</td></tr>");
                }
                
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Handle dynamic popups for success/error messages\r\n");
      out.write("    window.addEventListener('load', function () {\r\n");
      out.write("        const urlParams = new URLSearchParams(window.location.search);\r\n");
      out.write("        const successMessage = urlParams.get('success');\r\n");
      out.write("        const errorMessage = urlParams.get('error');\r\n");
      out.write("\r\n");
      out.write("        const popup = document.getElementById('popupMessage');\r\n");
      out.write("        const title = document.getElementById('popupTitle');\r\n");
      out.write("        const body = document.getElementById('popupBody');\r\n");
      out.write("\r\n");
      out.write("        if (successMessage) {\r\n");
      out.write("            switch (successMessage) {\r\n");
      out.write("                case 'userCreated':\r\n");
      out.write("                    title.innerText = 'User Created';\r\n");
      out.write("                    body.innerText = 'The user has been successfully created.';\r\n");
      out.write("                    break;\r\n");
      out.write("                case 'userDeleted':\r\n");
      out.write("                    title.innerText = 'User Deleted';\r\n");
      out.write("                    body.innerText = 'The user has been successfully deleted.';\r\n");
      out.write("                    break;\r\n");
      out.write("                case 'userEdited':\r\n");
      out.write("                    title.innerText = 'User Edited';\r\n");
      out.write("                    body.innerText = 'The user details have been successfully updated.';\r\n");
      out.write("                    break;\r\n");
      out.write("                default:\r\n");
      out.write("                    title.innerText = 'Success';\r\n");
      out.write("                    body.innerText = successMessage;\r\n");
      out.write("            }\r\n");
      out.write("            popup.classList.add('success');\r\n");
      out.write("            popup.style.display = 'block';\r\n");
      out.write("        } else if (errorMessage) {\r\n");
      out.write("            title.innerText = 'Error';\r\n");
      out.write("            body.innerText = errorMessage;\r\n");
      out.write("            popup.classList.add('error');\r\n");
      out.write("            popup.style.display = 'block';\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Close popup\r\n");
      out.write("    function closePopup() {\r\n");
      out.write("        const popup = document.getElementById('popupMessage');\r\n");
      out.write("        popup.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Filter rows in the user table based on search input\r\n");
      out.write("    function filterTable() {\r\n");
      out.write("        const input = document.getElementById('searchInput').value.toLowerCase();\r\n");
      out.write("        const rows = document.querySelectorAll('#userTable tbody tr');\r\n");
      out.write("\r\n");
      out.write("        rows.forEach(row => {\r\n");
      out.write("            const username = row.cells[0].innerText.toLowerCase();\r\n");
      out.write("            const email = row.cells[2].innerText.toLowerCase();\r\n");
      out.write("            const phone = row.cells[3].innerText.toLowerCase();\r\n");
      out.write("\r\n");
      out.write("            if (username.includes(input) || email.includes(input) || phone.includes(input)) {\r\n");
      out.write("                row.style.display = '';\r\n");
      out.write("            } else {\r\n");
      out.write("                row.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
